### ISSUE TITLE
-o, --output causes panic

### ISSUE THREAD

**Issue by danehans** [solo-io/supergloo#159]
I create the `RoutingRule`:
```
$ supergloo get routingrule reviews-v1
    |    NAME    | TARGET-MESH  | SOURCES |          DESTINTATIONS           | MATCHERS  
+---+------------+--------------+---------+----------------------------------+----------+
  1 | reviews-v1 | istio-m0228c |         | gloo-system:default-reviews-9080 |           
```

I then would like to look at the details of the resource which causes a panic:
```
$ supergloo get routingrule reviews-v1 -o yaml
panic: reflect: call of reflect.Value.Len on ptr Value

goroutine 1 [running]:
reflect.Value.Len(0x1f74b80, 0xc0006333c0, 0x16, 0x0)
	/usr/local/Cellar/go/1.11.4/libexec/src/reflect/value.go:1085 +0x1a8
github.com/solo-io/supergloo/vendor/github.com/solo-io/solo-kit/pkg/utils/cliutils.PrintYAMLList(0x1f74b80, 0xc0006333c0, 0x21b80a0, 0xc0000d2008, 0x1, 0x0)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/vendor/github.com/solo-io/solo-kit/pkg/utils/cliutils/printer.go:115 +0xee
github.com/solo-io/supergloo/vendor/github.com/solo-io/solo-kit/pkg/utils/cliutils.PrintList(0x7ffeefbff610, 0x4, 0x0, 0x0, 0x1f74b80, 0xc0006333c0, 0x20c5988, 0x21b80a0, 0xc0000d2008, 0xc0006b72f8, ...)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/vendor/github.com/solo-io/solo-kit/pkg/utils/cliutils/printer.go:73 +0x281
github.com/solo-io/supergloo/cli/pkg/cmd/get/printers.RoutingRuleTable(0xc0006333c0, 0x7ffeefbff610, 0x4, 0x0, 0x0, 0xc0006b72f8, 0x0)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/cli/pkg/cmd/get/printers/routingrule.go:19 +0x8d
github.com/solo-io/supergloo/cli/pkg/cmd/get.(*KubernetesInfoClient).ListResources(0xc0006333a0, 0x7ffeefbff610, 0x4, 0x7ffeefbff5f6, 0xb, 0x7ffeefbff602, 0xa, 0x203fe8f, 0x10, 0xc000084700, ...)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/cli/pkg/cmd/get/client.go:111 +0x39b
github.com/solo-io/supergloo/cli/pkg/cmd/get.getResource(0x21ba8a0, 0xc0006333a0, 0x7ffeefbff610, 0x4, 0x7ffeefbff5f6, 0xb, 0x7ffeefbff602, 0xa, 0x203fe8f, 0x10, ...)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/cli/pkg/cmd/get/get.go:92 +0x66
github.com/solo-io/supergloo/cli/pkg/cmd/get.get(0xc0000c92c0, 0x2, 0x4, 0x2dcdcc0, 0x0, 0x0)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/cli/pkg/cmd/get/get.go:51 +0xfe
github.com/solo-io/supergloo/cli/pkg/cmd/get.Cmd.func1(0xc000168f00, 0xc0000c92c0, 0x2, 0x4, 0x0, 0x0)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/cli/pkg/cmd/get/get.go:24 +0x48
github.com/solo-io/supergloo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000168f00, 0xc0000c9280, 0x4, 0x4, 0xc000168f00, 0xc0000c9280)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/solo-io/supergloo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ebb80, 0xc000100a00, 0xc000101400, 0xc000101680)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/solo-io/supergloo/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000ebb80, 0x10, 0xc0000ebb80)
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/Users/daneyonhansen/code/go/src/github.com/solo-io/supergloo/cli/cmd/main.go:18 +0xba
```

I get the same error if I specify json output and/or if I do not specify the `reviews-v1` resource name.

**Comment by ilackarms** [comment]
this should be fixed as of #160
